version: "3.5"

services:
  ng-dev:
    container_name: ng-docker-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "4201:4201"